apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application-deployment
  labels:
    app: web-application-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-application-deployment
  template:
    metadata:
      labels:
        app: web-application-deployment
    spec:
      containers:
      - name: web-application-deployment
        image: sankalpgunturi/ready:latest
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
