apiVersion: v1
kind: Service
metadata:
  name: web-application-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-application-deployment
