name: Deploy Web Application

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.NEW_GOOGLE_PROJECT_ID }}
        service_account_key: ${{ secrets.NEW_GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        

    - name: build and push the docker image
      run: |
        cd api
        docker build -t sankalpgunturi/ready:latest -f Dockerfile .
        docker push sankalpgunturi/ready:latest

    - name: deploy to gke
      env:
        GOOGLE_PROJECT_ID: ${{ secrets.NEW_GOOGLE_PROJECT_ID }}
      run: |
        gcloud container clusters get-credentials web-application-cluster --zone us-central1-c --project ${{ secrets.NEW_GOOGLE_PROJECT_ID }}
        kubectl delete deployment web-application-deployment
        cd infra
        kubectl apply -f deployment.yaml
