name: Deploy Web Application

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      run: |
        ls -al
        cd api
        docker build -t sankalpgunturi/ready:latest -f Dockerfile .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push sankalpgunturi/ready:latest

    - name: deploy to gke
      env:
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      run: |
        gcloud container clusters get-credentials web-application-cluster --project ${{ secrets.GOOGLE_PROJECT_ID }}
        terraform init
        terraform apply -auto-approve
